name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore DotNetEcuador.API/DotNetEcuador.API.csproj
      
    - name: Build application
      run: dotnet build DotNetEcuador.API/DotNetEcuador.API.csproj --configuration Release --no-restore
      
    - name: Publish application
      run: dotnet publish DotNetEcuador.API/DotNetEcuador.API.csproj -c Release -o ./publish --no-build
      
    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        source: "./publish/*"
        target: "/var/www/dotnetecuador-api/api-website-oficial/DotNetEcuador.API/publish/"
        strip_components: 1
        overwrite: true

    - name: Restart service and check status
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          sudo chown -R www-data:www-data /var/www/dotnetecuador-api/api-website-oficial/DotNetEcuador.API/publish/
          sudo chmod -R 755 /var/www/dotnetecuador-api/api-website-oficial/DotNetEcuador.API/publish/
          sudo systemctl restart dotnetecuador-api
          sleep 5
          sudo systemctl status dotnetecuador-api --no-pager
          echo "✅ Deployment completed successfully"